//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeronef
    {
        public int idAeronef { get; set; }
        public int idTypeAeronef { get; set; }
        public Nullable<int> poidsCargaison { get; set; }
        public Nullable<int> integriteBlindage { get; set; }
        public Nullable<int> jaugeCarburant { get; set; }
        public Nullable<int> idJoueur { get; set; }
        public Nullable<int> vitesse { get; set; }
    
        public virtual Joueur Joueur { get; set; }
        public virtual TypeAeronef TypeAeronef { get; set; }
    }
}
