//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventaire
    {
        public int idInventaire { get; set; }
        public int quantite { get; set; }
        public int idJoueur { get; set; }
        public int idRessource { get; set; }
    
        public virtual Joueur Joueur { get; set; }
        public virtual Ressource Ressource { get; set; }
    }
}
