//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messagerie
    {
        public int idMessagerie { get; set; }
        public string typeMessagerie { get; set; }
        public string textMessagerie { get; set; }
        public Nullable<int> idJoueur { get; set; }
        public Nullable<int> idEnvironnement { get; set; }
    
        public virtual Environnement Environnement { get; set; }
        public virtual Joueur Joueur { get; set; }
    }
}
