//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EarthRescueEntities : DbContext
    {
        public EarthRescueEntities()
            : base("name=EarthRescueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actions> Actions { get; set; }
        public virtual DbSet<Aeronef> Aeronef { get; set; }
        public virtual DbSet<Ennemi> Ennemi { get; set; }
        public virtual DbSet<Environnement> Environnement { get; set; }
        public virtual DbSet<EnvironnementRessource> EnvironnementRessource { get; set; }
        public virtual DbSet<Inventaire> Inventaire { get; set; }
        public virtual DbSet<Joueur> Joueur { get; set; }
        public virtual DbSet<Messagerie> Messagerie { get; set; }
        public virtual DbSet<Music> Music { get; set; }
        public virtual DbSet<NiveauEnvironnement> NiveauEnvironnement { get; set; }
        public virtual DbSet<NiveauJoueur> NiveauJoueur { get; set; }
        public virtual DbSet<Objectif> Objectif { get; set; }
        public virtual DbSet<Parametre> Parametre { get; set; }
        public virtual DbSet<ParametreJoueur> ParametreJoueur { get; set; }
        public virtual DbSet<Partie> Partie { get; set; }
        public virtual DbSet<Ressource> Ressource { get; set; }
        public virtual DbSet<SpawnEnnemi> SpawnEnnemi { get; set; }
        public virtual DbSet<TypeAeronef> TypeAeronef { get; set; }
        public virtual DbSet<TypeEnnemi> TypeEnnemi { get; set; }
        public virtual DbSet<TypeEnvironnement> TypeEnvironnement { get; set; }
        public virtual DbSet<TypeMusic> TypeMusic { get; set; }
        public virtual DbSet<TypeRessource> TypeRessource { get; set; }
    }
}
