//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiveauEnvironnement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NiveauEnvironnement()
        {
            this.Environnement = new HashSet<Environnement>();
        }
    
        public int idNiveauEnvironnement { get; set; }
        public string nomNiveauEnvironnement { get; set; }
        public string model3Dreconstruction { get; set; }
        public Nullable<int> niveauEnnemis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Environnement> Environnement { get; set; }
    }
}
