//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objectif
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objectif()
        {
            this.Partie = new HashSet<Partie>();
        }
    
        public int idObjectif { get; set; }
        public string nomObjectif { get; set; }
        public string texteObjectif { get; set; }
        public Nullable<int> niveauObjectif { get; set; }
        public Nullable<int> ordreObjectif { get; set; }
        public Nullable<int> IdTypeEnnemi { get; set; }
        public Nullable<int> IdTypeRessource { get; set; }
        public int Quantite { get; set; }
        public int IdEnvironnement { get; set; }
    
        public virtual Environnement Environnement { get; set; }
        public virtual TypeEnnemi TypeEnnemi { get; set; }
        public virtual TypeRessource TypeRessource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partie> Partie { get; set; }
    }
}
