//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpawnEnnemi
    {
        public int idSpawnEnnemi { get; set; }
        public int idTypeEnvironnement { get; set; }
        public int idTypeEnnemi { get; set; }
        public int nbreEnnemis { get; set; }
    
        public virtual TypeEnvironnement TypeEnvironnement { get; set; }
        public virtual TypeEnnemi TypeEnnemi { get; set; }
    }
}
