//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeAeronef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeAeronef()
        {
            this.Aeronef = new HashSet<Aeronef>();
        }
    
        public int idTypeAeronef { get; set; }
        public string nomTypeAeronef { get; set; }
        public Nullable<int> degatsLasersAeronef { get; set; }
        public Nullable<int> cargaisonMaxAeronef { get; set; }
        public Nullable<int> prixAeronef { get; set; }
        public Nullable<int> blindageMaxAeronef { get; set; }
        public Nullable<int> capaciteCarburantMax { get; set; }
        public string model3dAeronef { get; set; }
        public string sonAeronef { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aeronef> Aeronef { get; set; }
    }
}
