//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeEnnemi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeEnnemi()
        {
            this.Ennemi = new HashSet<Ennemi>();
            this.Objectif = new HashSet<Objectif>();
            this.SpawnEnnemi = new HashSet<SpawnEnnemi>();
        }
    
        public int idTypeEnnemi { get; set; }
        public string nomTypeEnnemi { get; set; }
        public int vieMaxEnnemi { get; set; }
        public int puissanceTypeEnnemi { get; set; }
        public double vitesseTypeEnnemi { get; set; }
        public Nullable<int> idTypeEnvironnement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ennemi> Ennemi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Objectif> Objectif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpawnEnnemi> SpawnEnnemi { get; set; }
        public virtual TypeEnvironnement TypeEnvironnement { get; set; }
    }
}
